name: markid
description: "Detects ArUco Markers and AprilTags and tells you their IDs."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  opencv_core: ^1.4.3
  camera: ^0.11.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/logo.png"

hooks:
  user_defines:
    dartcv4:
      exclude_modules:
        - calib3d
        - contrib
        - dnn
        - features2d
        - flann
        - highgui
        - objdetect
        - photo
        - stitching
        - video
        - videoio