name: Build artifacts
on:
  push:
    paths-ignore:
      - "**.md"
      - "LICENSE"
jobs:
  android:
      name: android-size-comparison
      runs-on: ubuntu-latest
      steps:
        - uses: subosito/flutter-action@v2
          with:
            channel: "stable"
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            distribution: "temurin"
            java-version: "17"

        - name: Build project
          run: |
            flutter create base_project
            flutter build apk --release --split-per-abi

        - uses: actions/upload-artifact@v4
          with:
            name: base_project_apks
            paths: build/app/outputs/flutter-apk//