name: Build artifacts
on:
  push:
    paths-ignore:
      - "**.md"
      - "LICENSE"
jobs:
  android:
    name: android-build
    runs-on: ubuntu-latest
    steps:
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build project
        run: |
          flutter create markid
          flutter build apk --release --split-per-abi

      - uses: actions/upload-artifact@v4
        with:
          name: apks
          path: build/app/outputs/flutter-apk/